BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 1. USERS TABLE (NFC-based user identification)
-- ============================================

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nfc_tag_id VARCHAR(100) UNIQUE NOT NULL,
    user_name VARCHAR(100),
    user_password VARCHAR(255),
    name VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_interaction TIMESTAMPTZ,
    traits JSONB NOT NULL DEFAULT '[]'::jsonb,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    memory JSONB NOT NULL DEFAULT '[]'::jsonb
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS user_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS user_password VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS chk_users_user_name_format,
    DROP CONSTRAINT IF EXISTS chk_users_name_format;

ALTER TABLE users
    ADD CONSTRAINT chk_users_user_name_format
    CHECK (user_name IS NULL OR user_name ~ '^[A-Za-z0-9_]+$'),
    ADD CONSTRAINT chk_users_name_format
    CHECK (name IS NULL OR btrim(name) <> '' AND name ~ '^[[:alpha:][:space:]]+$');

CREATE INDEX IF NOT EXISTS idx_nfc_tag_id ON users (nfc_tag_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_name ON users (user_name);
COMMENT ON COLUMN users.user_password IS 'Stores a password hash generated by the application.';

-- ============================================
-- 2. ALARMS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS alarms (
    alarm_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    time TIME NOT NULL,
    label VARCHAR(255) NOT NULL,
    repeat VARCHAR(20) NOT NULL DEFAULT 'once' CHECK (repeat IN ('once', 'daily', 'weekly')),
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_alarms ON alarms (user_id);
DROP TRIGGER IF EXISTS set_alarms_updated_at ON alarms;
CREATE TRIGGER set_alarms_updated_at
BEFORE UPDATE ON alarms
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 3. TIMERS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS timers (
    timer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    label VARCHAR(255) NOT NULL,
    duration_seconds INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_timers ON timers (user_id);

-- ============================================
-- 4. LISTS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS lists (
    list_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    list_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_lists ON lists (user_id);
DROP TRIGGER IF EXISTS set_lists_updated_at ON lists;
CREATE TRIGGER set_lists_updated_at
BEFORE UPDATE ON lists
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 5. LIST_ITEMS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS list_items (
    item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    list_id UUID NOT NULL REFERENCES lists(list_id) ON DELETE CASCADE,
    content VARCHAR(500) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_list_items ON list_items (list_id);
DROP TRIGGER IF EXISTS set_list_items_updated_at ON list_items;
CREATE TRIGGER set_list_items_updated_at
BEFORE UPDATE ON list_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================
-- 6. INTERACTION_LOGS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS interaction_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    input_text VARCHAR(1000),
    output_text VARCHAR(2000),
    intent VARCHAR(50),
    tools_called JSONB NOT NULL DEFAULT '[]'::jsonb,
    latency_ms INTEGER,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_logs_user_time ON interaction_logs (user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_intent ON interaction_logs (intent);

COMMIT;
